<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BarangMasukSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'kode_barang' => '2312312',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang A',
                'kategori' => 'Stock',
                'harga_beli' => 10000,
                'kuantiti' => 10,
                'deskripsi_barang' => 'Deskripsi Barang A',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123456',
                'tempat_penyimpanan' => 'Gudang A',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312313',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang B',
                'kategori' => 'Stock',
                'harga_beli' => 15000,
                'kuantiti' => 5,
                'deskripsi_barang' => 'Deskripsi Barang B',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123457',
                'tempat_penyimpanan' => 'Gudang B',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312314',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang C',
                'kategori' => 'Consumable',
                'harga_beli' => 5000,
                'kuantiti' => 20,
                'deskripsi_barang' => 'Deskripsi Barang C',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123458',
                'tempat_penyimpanan' => 'Gudang C',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312315',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang D',
                'kategori' => 'Stock',
                'harga_beli' => 20000,
                'kuantiti' => 15,
                'deskripsi_barang' => 'Deskripsi Barang D',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123459',
                'tempat_penyimpanan' => 'Gudang D',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312316',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang E',
                'kategori' => 'Consumable',
                'harga_beli' => 3000,
                'kuantiti' => 50,
                'deskripsi_barang' => 'Deskripsi Barang E',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123460',
                'tempat_penyimpanan' => 'Gudang E',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312317',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang F',
                'kategori' => 'Stock',
                'harga_beli' => 12000,
                'kuantiti' => 8,
                'deskripsi_barang' => 'Deskripsi Barang F',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123461',
                'tempat_penyimpanan' => 'Gudang F',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312318',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang G',
                'kategori' => 'Consumable',
                'harga_beli' => 7000,
                'kuantiti' => 30,
                'deskripsi_barang' => 'Deskripsi Barang G',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123462',
                'tempat_penyimpanan' => 'Gudang G',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312319',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang H',
                'kategori' => 'Stock',
                'harga_beli' => 25000,
                'kuantiti' => 12,
                'deskripsi_barang' => 'Deskripsi Barang H',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123463',
                'tempat_penyimpanan' => 'Gudang H',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312320',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang I',
                'kategori' => 'Consumable',
                'harga_beli' => 4000,
                'kuantiti' => 25,
                'deskripsi_barang' => 'Deskripsi Barang I',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123464',
                'tempat_penyimpanan' => 'Gudang I',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312321',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang J',
                'kategori' => 'Stock',
                'harga_beli' => 18000,
                'kuantiti' => 7,
                'deskripsi_barang' => 'Deskripsi Barang J',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123465',
                'tempat_penyimpanan' => 'Gudang J',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312322',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang K',
                'kategori' => 'Consumable',
                'harga_beli' => 6000,
                'kuantiti' => 40,
                'deskripsi_barang' => 'Deskripsi Barang K',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123466',
                'tempat_penyimpanan' => 'Gudang K',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312323',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang L',
                'kategori' => 'Stock',
                'harga_beli' => 22000,
                'kuantiti' => 9,
                'deskripsi_barang' => 'Deskripsi Barang L',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123467',
                'tempat_penyimpanan' => 'Gudang L',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312324',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang M',
                'kategori' => 'Consumable',
                'harga_beli' => 8000,
                'kuantiti' => 35,
                'deskripsi_barang' => 'Deskripsi Barang M',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123468',
                'tempat_penyimpanan' => 'Gudang M',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312325',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang N',
                'kategori' => 'Stock',
                'harga_beli' => 13000,
                'kuantiti' => 11,
                'deskripsi_barang' => 'Deskripsi Barang N',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123469',
                'tempat_penyimpanan' => 'Gudang N',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312326',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang O',
                'kategori' => 'Consumable',
                'harga_beli' => 9000,
                'kuantiti' => 28,
                'deskripsi_barang' => 'Deskripsi Barang O',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123470',
                'tempat_penyimpanan' => 'Gudang O',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312327',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang P',
                'kategori' => 'Stock',
                'harga_beli' => 17000,
                'kuantiti' => 6,
                'deskripsi_barang' => 'Deskripsi Barang P',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123471',
                'tempat_penyimpanan' => 'Gudang P',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312328',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang Q',
                'kategori' => 'Consumable',
                'harga_beli' => 11000,
                'kuantiti' => 22,
                'deskripsi_barang' => 'Deskripsi Barang Q',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123472',
                'tempat_penyimpanan' => 'Gudang Q',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312329',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang R',
                'kategori' => 'Stock',
                'harga_beli' => 14000,
                'kuantiti' => 14,
                'deskripsi_barang' => 'Deskripsi Barang R',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123473',
                'tempat_penyimpanan' => 'Gudang R',
                'tanggal_masuk' => Carbon::now(),
            ],
            [
                'kode_barang' => '2312330',
                'attachment_gambar' => null,
                'nama_barang' => 'Barang S',
                'kategori' => 'Consumable',
                'harga_beli' => 9500,
                'kuantiti' => 18,
                'deskripsi_barang' => 'Deskripsi Barang S',
                'vendor' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'status' => 'pending',
                'tipe_barang' => '2313',
                'serial_number' => 'SN123474',
                'tempat_penyimpanan' => 'Gudang S',
                'tanggal_masuk' => Carbon::now(),
            ],
        ];

        // Menggunakan DB::table untuk memasukkan data
        DB::table('barang_masuk')->insert($data);
    }
}
